PA-6132: Back-Port OpenSSL 1.1.1 for agent-runtime-7.x
puppetlabs/puppet-runtime pull request #794
Opened 2024-02-23 10:32 UTC by span786

Applied CVE patches for openssl-1.1.1v :
1. CVE-2023-5678
2. CVE-2024-0727

Applied patched for openssl-1.1.1k-7-fips:
1. CVE-2023-3446 (Required for CVE-2023-5678 patch to apply without errors)
2. CVE-2023-5678
3. CVE-2024-0727

2024-02-23 19:45 UTC, joshcooper commented
I kicked off generic builder for all `agent-runtime-7.x` platforms in https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-generic-builder-init_generic-builder/2851/

2024-02-23 21:13 UTC, joshcooper requested changes
Build failed on rhelfips-7

https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2686/

May also be an issue on sles-12? I rekicked it to be sure

2024-02-26 17:53 UTC, joshcooper commented
@span786 since commit https://github.com/puppetlabs/puppet-runtime/pull/794/commits/c8e7f20819f59b36d2cf729d5e17f5ea94aaa048 reverts https://github.com/puppetlabs/puppet-runtime/pull/794/commits/832549bc09bc046772a27ed3ba4414abba00293e and both are in this PR, can you drop both commits?

2024-02-27 05:31 UTC, span786 commented
Closing this PR. Raised a separate PR (https://github.com/puppetlabs/puppet-runtime/pull/797) which contains clean commits

2024-02-27 05:31 UTC, closed without merging